service: hands-on-serverless

provider:
  name: aws
  runtime: nodejs16.x

package:
  excludeDevDependencies: true
  individually: true
  
plugins:
  - serverless-offline

functions:
  hello:
    handler: src/index.handler
    events:
        - http:
            path: /api
            method: GET